import 'package:flutter/material.dart';

final curves = [
  Curves.linear,
  Curves.decelerate,
  Curves.fastLinearToSlowEaseIn,
  Curves.ease,
  Curves.easeIn,
  Curves.easeInToLinear,
  Curves.easeInSine,
  Curves.easeInQuad,
  Curves.easeInCubic,
  Curves.easeInQuart,
  Curves.easeInQuint,
  Curves.easeInExpo,
  Curves.easeInCirc,
  Curves.easeInBack,
  Curves.easeOut,
  Curves.linearToEaseOut,
  Curves.easeOutSine,
  Curves.easeOutQuad,
  Curves.easeOutCubic,
  Curves.easeOutQuart,
  Curves.easeOutQuint,
  Curves.easeOutExpo,
  Curves.easeOutCirc,
  Curves.easeOutBack,
  Curves.easeInOut,
  Curves.easeInOutSine,
  Curves.easeInOutQuad,
  Curves.easeInOutCubic,
  Curves.easeInOutQuart,
  Curves.easeInOutQuint,
  Curves.easeInOutExpo,
  Curves.easeInOutCirc,
  Curves.easeInOutBack,
  Curves.fastOutSlowIn,
  Curves.slowMiddle,
  Curves.bounceIn,
  Curves.bounceOut,
  Curves.bounceInOut,
  Curves.elasticIn,
  Curves.elasticOut,
  Curves.elasticInOut,
];

extension CurvesExtension on Curve {
  String get name => switch (this) {
        (Curves.linear) => "Linear",
        (Curves.decelerate) => "Decelerate",
        (Curves.fastLinearToSlowEaseIn) => "FastLinearToSlowEaseIn",
        (Curves.ease) => "Ease",
        (Curves.easeIn) => "EaseIn",
        (Curves.easeInToLinear) => "EaseInToLinear",
        (Curves.easeInSine) => "EaseInSine",
        (Curves.easeInQuad) => "EaseInQuad",
        (Curves.easeInCubic) => "EaseInCubic",
        (Curves.easeInQuart) => "EaseInQuart",
        (Curves.easeInQuint) => "EaseInQuint",
        (Curves.easeInExpo) => "EaseInExpo",
        (Curves.easeInCirc) => "EaseInCirc",
        (Curves.easeInBack) => "EaseInBack",
        (Curves.easeOut) => "EaseOut",
        (Curves.linearToEaseOut) => "LinearToEaseOut",
        (Curves.easeOutSine) => "EaseOutSine",
        (Curves.easeOutQuad) => "EaseOutQuad",
        (Curves.easeOutCubic) => "EaseOutCubic",
        (Curves.easeOutQuart) => "EaseOutQuart",
        (Curves.easeOutQuint) => "EaseOutQuint",
        (Curves.easeOutExpo) => "EaseOutExpo",
        (Curves.easeOutCirc) => "EaseOutCirc",
        (Curves.easeOutBack) => "EaseOutBack",
        (Curves.easeInOut) => "EaseInOut",
        (Curves.easeInOutSine) => "EaseInOutSine",
        (Curves.easeInOutQuad) => "EaseInOutQuad",
        (Curves.easeInOutCubic) => "EaseInOutCubic",
        (Curves.easeInOutQuart) => "EaseInOutQuart",
        (Curves.easeInOutQuint) => "EaseInOutQuint",
        (Curves.easeInOutExpo) => "EaseInOutExpo",
        (Curves.easeInOutCirc) => "EaseInOutCirc",
        (Curves.easeInOutBack) => "EaseInOutBack",
        (Curves.fastOutSlowIn) => "FastOutSlowIn",
        (Curves.slowMiddle) => "SlowMiddle",
        (Curves.bounceIn) => "BounceIn",
        (Curves.bounceOut) => "BounceOut",
        (Curves.bounceInOut) => "BounceInOut",
        (Curves.elasticIn) => "ElasticIn",
        (Curves.elasticOut) => "ElasticOut",
        (Curves.elasticInOut) => "ElasticInOut",
        _ => "Custom",
      };
}
